import {
  FaReact,
  FaPython,
  FaJs,
  FaNodeJs,
  FaGitAlt,
  FaTerminal,
  FaCode,
  FaHtml5,
  FaCss3,
  FaSass,
  FaDocker,
  FaAws,
  FaBootstrap,
  FaLinux,
  FaUbuntu,
  FaDatabase,
  FaServer,
  FaCogs,
  FaCubes,
  FaPencilAlt,
  FaVial,
  FaBug,
} from "react-icons/fa";
import type { FC } from "react";

type WorkingIconType = FC<{ size: number; className: string }>;

interface IconConfig {
  Icon: WorkingIconType;
  size: number;
  opacity: number;
  position: { top: string; left: string };
  depth: number;
}

export const icons: IconConfig[] = [
  {
    Icon: FaReact,
    size: 120,
    opacity: 0.1,
    position: { top: "5%", left: "1%" },
    depth: 5,
  },
  {
    Icon: FaPython,
    size: 80,
    opacity: 0.12,
    position: { top: "15%", left: "95%" },
    depth: 7,
  },
  {
    Icon: FaJs,
    size: 150,
    opacity: 0.08,
    position: { top: "60%", left: "5%" },
    depth: 4,
  },
  {
    Icon: FaDocker,
    size: 90,
    opacity: 0.1,
    position: { top: "85%", left: "50%" },
    depth: 6,
  },
  {
    Icon: FaHtml5,
    size: 70,
    opacity: 0.12,
    position: { top: "10%", left: "70%" },
    depth: 5,
  },
  {
    Icon: FaCss3,
    size: 100,
    opacity: 0.08,
    position: { top: "40%", left: "30%" },
    depth: 4,
  },
  {
    Icon: FaTerminal,
    size: 180,
    opacity: 0.05,
    position: { top: "50%", left: "90%" },
    depth: 3,
  },
  {
    Icon: FaSass,
    size: 90,
    opacity: 0.1,
    position: { top: "70%", left: "15%" },
    depth: 7,
  },
  {
    Icon: FaDatabase,
    size: 70,
    opacity: 0.12,
    position: { top: "25%", left: "55%" },
    depth: 5,
  },
  {
    Icon: FaServer,
    size: 110,
    opacity: 0.09,
    position: { top: "80%", left: "75%" },
    depth: 6,
  },
  {
    Icon: FaNodeJs,
    size: 110,
    opacity: 0.2,
    position: { top: "35%", left: "5%" },
    depth: 15,
  },
  {
    Icon: FaGitAlt,
    size: 95,
    opacity: 0.18,
    position: { top: "75%", left: "25%" },
    depth: 13,
  },
  {
    Icon: FaBootstrap,
    size: 70,
    opacity: 0.22,
    position: { top: "1%", left: "40%" },
    depth: 16,
  },
  {
    Icon: FaAws,
    size: 130,
    opacity: 0.15,
    position: { top: "90%", left: "60%" },
    depth: 14,
  },
  {
    Icon: FaCode,
    size: 80,
    opacity: 0.2,
    position: { top: "50%", left: "65%" },
    depth: 17,
  },
  {
    Icon: FaLinux,
    size: 100,
    opacity: 0.16,
    position: { top: "65%", left: "40%" },
    depth: 15,
  },
  {
    Icon: FaUbuntu,
    size: 75,
    opacity: 0.2,
    position: { top: "15%", left: "20%" },
    depth: 18,
  },
  {
    Icon: FaCogs,
    size: 90,
    opacity: 0.17,
    position: { top: "45%", left: "95%" },
    depth: 12,
  },
  {
    Icon: FaCubes,
    size: 60,
    opacity: 0.25,
    position: { top: "95%", left: "10%" },
    depth: 16,
  },
  {
    Icon: FaPencilAlt,
    size: 80,
    opacity: 0.18,
    position: { top: "30%", left: "80%" },
    depth: 14,
  },
  {
    Icon: FaJs,
    size: 50,
    opacity: 0.3,
    position: { top: "20%", left: "10%" },
    depth: 25,
  },
  {
    Icon: FaReact,
    size: 60,
    opacity: 0.25,
    position: { top: "70%", left: "60%" },
    depth: 22,
  },
  {
    Icon: FaCode,
    size: 40,
    opacity: 0.35,
    position: { top: "80%", left: "5%" },
    depth: 28,
  },
  {
    Icon: FaVial,
    size: 70,
    opacity: 0.28,
    position: { top: "5%", left: "85%" },
    depth: 20,
  },
  {
    Icon: FaBug,
    size: 55,
    opacity: 0.32,
    position: { top: "80%", left: "30%" },
    depth: 26,
  },
  {
    Icon: FaPython,
    size: 45,
    opacity: 0.38,
    position: { top: "40%", left: "25%" },
    depth: 24,
  },
  {
    Icon: FaDocker,
    size: 65,
    opacity: 0.28,
    position: { top: "60%", left: "70%" },
    depth: 21,
  },
  {
    Icon: FaGitAlt,
    size: 50,
    opacity: 0.3,
    position: { top: "10%", left: "30%" },
    depth: 27,
  },
  {
    Icon: FaHtml5,
    size: 70,
    opacity: 0.25,
    position: { top: "65%", left: "95%" },
    depth: 23,
  },
  {
    Icon: FaCss3,
    size: 40,
    opacity: 0.33,
    position: { top: "95%", left: "90%" },
    depth: 29,
  },
];
